app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_author:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_task:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_success:
    resource: "@AppBundle/Controller/"
    type:     annotation